### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by cupiditys** [HypnoticLOL/HypnoticLOL-s-Menu#2]
kinda weird but can you dm me deobfuscated source cuz I can’t get on my main pc for a few hours and the only place I have it stored just so happens to be that pc

**Comment by HypnoticLOL** [comment]
hold up a sec

**Comment by HypnoticLOL** [comment]
1 how I dm, 2 is it ok if the html is mine? cuz I can delete what I added in js but its kinda harder to do it in html

**Comment by cupiditys** [comment]
yea its fine

**Comment by cupiditys** [comment]
add on discord cupiditys#2113

**Comment by HypnoticLOL** [comment]
done
